package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpic062ExpPizarra generated by hbm2java
 */
@Entity
@Table(name = "TPIC062_EXP_PIZARRA")
public class Tpic062ExpPizarra implements java.io.Serializable {

	private BigDecimal cdPiz;
	private Integer nuPizIrCompromiso;
	private Integer nuPizIrReal;
	private Integer nuPizRgCompromiso;
	private Integer nuPizRgReal;
	private Integer nuPizCancelacion;
	private Date fhPiz;
	private String txPizOficina;
	private Tpic063ExpDpizarr tpic063ExpDpizarr;

	public Tpic062ExpPizarra() {
	}

	public Tpic062ExpPizarra(BigDecimal cdPiz) {
		this.cdPiz = cdPiz;
	}

	public Tpic062ExpPizarra(BigDecimal cdPiz, Integer nuPizIrCompromiso, Integer nuPizIrReal,
			Integer nuPizRgCompromiso, Integer nuPizRgReal, Integer nuPizCancelacion, Date fhPiz, String txPizOficina,
			Tpic063ExpDpizarr tpic063ExpDpizarr) {
		this.cdPiz = cdPiz;
		this.nuPizIrCompromiso = nuPizIrCompromiso;
		this.nuPizIrReal = nuPizIrReal;
		this.nuPizRgCompromiso = nuPizRgCompromiso;
		this.nuPizRgReal = nuPizRgReal;
		this.nuPizCancelacion = nuPizCancelacion;
		this.fhPiz = fhPiz;
		this.txPizOficina = txPizOficina;
		this.tpic063ExpDpizarr = tpic063ExpDpizarr;
	}

	@Id

	@Column(name = "CD_PIZ", unique = true, nullable = false, scale = 0)
	public BigDecimal getCdPiz() {
		return this.cdPiz;
	}

	public void setCdPiz(BigDecimal cdPiz) {
		this.cdPiz = cdPiz;
	}

	@Column(name = "NU_PIZ_IR_COMPROMISO", precision = 5, scale = 0)
	public Integer getNuPizIrCompromiso() {
		return this.nuPizIrCompromiso;
	}

	public void setNuPizIrCompromiso(Integer nuPizIrCompromiso) {
		this.nuPizIrCompromiso = nuPizIrCompromiso;
	}

	@Column(name = "NU_PIZ_IR_REAL", precision = 5, scale = 0)
	public Integer getNuPizIrReal() {
		return this.nuPizIrReal;
	}

	public void setNuPizIrReal(Integer nuPizIrReal) {
		this.nuPizIrReal = nuPizIrReal;
	}

	@Column(name = "NU_PIZ_RG_COMPROMISO", precision = 5, scale = 0)
	public Integer getNuPizRgCompromiso() {
		return this.nuPizRgCompromiso;
	}

	public void setNuPizRgCompromiso(Integer nuPizRgCompromiso) {
		this.nuPizRgCompromiso = nuPizRgCompromiso;
	}

	@Column(name = "NU_PIZ_RG_REAL", precision = 5, scale = 0)
	public Integer getNuPizRgReal() {
		return this.nuPizRgReal;
	}

	public void setNuPizRgReal(Integer nuPizRgReal) {
		this.nuPizRgReal = nuPizRgReal;
	}

	@Column(name = "NU_PIZ_CANCELACION", precision = 5, scale = 0)
	public Integer getNuPizCancelacion() {
		return this.nuPizCancelacion;
	}

	public void setNuPizCancelacion(Integer nuPizCancelacion) {
		this.nuPizCancelacion = nuPizCancelacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_PIZ", length = 7)
	public Date getFhPiz() {
		return this.fhPiz;
	}

	public void setFhPiz(Date fhPiz) {
		this.fhPiz = fhPiz;
	}

	@Column(name = "TX_PIZ_OFICINA", length = 50)
	public String getTxPizOficina() {
		return this.txPizOficina;
	}

	public void setTxPizOficina(String txPizOficina) {
		this.txPizOficina = txPizOficina;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tpic062ExpPizarra")
	public Tpic063ExpDpizarr getTpic063ExpDpizarr() {
		return this.tpic063ExpDpizarr;
	}

	public void setTpic063ExpDpizarr(Tpic063ExpDpizarr tpic063ExpDpizarr) {
		this.tpic063ExpDpizarr = tpic063ExpDpizarr;
	}

}
