package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tpic063ExpDpizarr generated by hbm2java
 */
@Entity
@Table(name = "TPIC063_EXP_DPIZARR")
public class Tpic063ExpDpizarr implements java.io.Serializable {

	private BigDecimal cdPiz;
	private Tpic062ExpPizarra tpic062ExpPizarra;
	private Integer nuPizCompromiso;
	private Integer nuPizReal;

	public Tpic063ExpDpizarr() {
	}

	public Tpic063ExpDpizarr(Tpic062ExpPizarra tpic062ExpPizarra) {
		this.tpic062ExpPizarra = tpic062ExpPizarra;
	}

	public Tpic063ExpDpizarr(Tpic062ExpPizarra tpic062ExpPizarra, Integer nuPizCompromiso, Integer nuPizReal) {
		this.tpic062ExpPizarra = tpic062ExpPizarra;
		this.nuPizCompromiso = nuPizCompromiso;
		this.nuPizReal = nuPizReal;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tpic062ExpPizarra"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "CD_PIZ", unique = true, nullable = false, scale = 0)
	public BigDecimal getCdPiz() {
		return this.cdPiz;
	}

	public void setCdPiz(BigDecimal cdPiz) {
		this.cdPiz = cdPiz;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tpic062ExpPizarra getTpic062ExpPizarra() {
		return this.tpic062ExpPizarra;
	}

	public void setTpic062ExpPizarra(Tpic062ExpPizarra tpic062ExpPizarra) {
		this.tpic062ExpPizarra = tpic062ExpPizarra;
	}

	@Column(name = "NU_PIZ_COMPROMISO", precision = 5, scale = 0)
	public Integer getNuPizCompromiso() {
		return this.nuPizCompromiso;
	}

	public void setNuPizCompromiso(Integer nuPizCompromiso) {
		this.nuPizCompromiso = nuPizCompromiso;
	}

	@Column(name = "NU_PIZ_REAL", precision = 5, scale = 0)
	public Integer getNuPizReal() {
		return this.nuPizReal;
	}

	public void setNuPizReal(Integer nuPizReal) {
		this.nuPizReal = nuPizReal;
	}

}
