package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpic064ExpRoperac generated by hbm2java
 */
@Entity
@Table(name = "TPIC064_EXP_ROPERAC")
public class Tpic064ExpRoperac implements java.io.Serializable {

	private BigDecimal cdReg;
	private Integer txRegMeta;
	private Integer txRegAvance;
	private Date fhRegFecha;
	private String txRegMes;
	private Tpic065ExpDregist tpic065ExpDregist;

	public Tpic064ExpRoperac() {
	}

	public Tpic064ExpRoperac(BigDecimal cdReg) {
		this.cdReg = cdReg;
	}

	public Tpic064ExpRoperac(BigDecimal cdReg, Integer txRegMeta, Integer txRegAvance, Date fhRegFecha, String txRegMes,
			Tpic065ExpDregist tpic065ExpDregist) {
		this.cdReg = cdReg;
		this.txRegMeta = txRegMeta;
		this.txRegAvance = txRegAvance;
		this.fhRegFecha = fhRegFecha;
		this.txRegMes = txRegMes;
		this.tpic065ExpDregist = tpic065ExpDregist;
	}

	@Id

	@Column(name = "CD_REG", unique = true, nullable = false, scale = 0)
	public BigDecimal getCdReg() {
		return this.cdReg;
	}

	public void setCdReg(BigDecimal cdReg) {
		this.cdReg = cdReg;
	}

	@Column(name = "TX_REG_META", precision = 5, scale = 0)
	public Integer getTxRegMeta() {
		return this.txRegMeta;
	}

	public void setTxRegMeta(Integer txRegMeta) {
		this.txRegMeta = txRegMeta;
	}

	@Column(name = "TX_REG_AVANCE", precision = 5, scale = 0)
	public Integer getTxRegAvance() {
		return this.txRegAvance;
	}

	public void setTxRegAvance(Integer txRegAvance) {
		this.txRegAvance = txRegAvance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_REG_FECHA", length = 7)
	public Date getFhRegFecha() {
		return this.fhRegFecha;
	}

	public void setFhRegFecha(Date fhRegFecha) {
		this.fhRegFecha = fhRegFecha;
	}

	@Column(name = "TX_REG_MES", length = 15)
	public String getTxRegMes() {
		return this.txRegMes;
	}

	public void setTxRegMes(String txRegMes) {
		this.txRegMes = txRegMes;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tpic064ExpRoperac")
	public Tpic065ExpDregist getTpic065ExpDregist() {
		return this.tpic065ExpDregist;
	}

	public void setTpic065ExpDregist(Tpic065ExpDregist tpic065ExpDregist) {
		this.tpic065ExpDregist = tpic065ExpDregist;
	}

}
