package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tpic060ExpTuberia generated by hbm2java
 */
@Entity
@Table(name = "TPIC060_EXP_TUBERIA")
public class Tpic060ExpTuberia implements java.io.Serializable {

	private BigDecimal cdTub;
	private Serializable tmCreacion;
	private Serializable tmEdicion;
	private BigDecimal cdCreador;
	private BigDecimal cdEditor;
	private BigDecimal nuTubOferta;
	private BigDecimal nuTubVisita;
	private Set<Tpic061ExpOperaci> tpic061ExpOperacis = new HashSet<Tpic061ExpOperaci>(0);

	public Tpic060ExpTuberia() {
	}

	public Tpic060ExpTuberia(BigDecimal cdTub) {
		this.cdTub = cdTub;
	}

	public Tpic060ExpTuberia(BigDecimal cdTub, Serializable tmCreacion, Serializable tmEdicion, BigDecimal cdCreador,
			BigDecimal cdEditor, BigDecimal nuTubOferta, BigDecimal nuTubVisita,
			Set<Tpic061ExpOperaci> tpic061ExpOperacis) {
		this.cdTub = cdTub;
		this.tmCreacion = tmCreacion;
		this.tmEdicion = tmEdicion;
		this.cdCreador = cdCreador;
		this.cdEditor = cdEditor;
		this.nuTubOferta = nuTubOferta;
		this.nuTubVisita = nuTubVisita;
		this.tpic061ExpOperacis = tpic061ExpOperacis;
	}

	@Id

	@Column(name = "CD_TUB", unique = true, nullable = false, scale = 0)
	public BigDecimal getCdTub() {
		return this.cdTub;
	}

	public void setCdTub(BigDecimal cdTub) {
		this.cdTub = cdTub;
	}

	@Column(name = "TM_CREACION")
	public Serializable getTmCreacion() {
		return this.tmCreacion;
	}

	public void setTmCreacion(Serializable tmCreacion) {
		this.tmCreacion = tmCreacion;
	}

	@Column(name = "TM_EDICION")
	public Serializable getTmEdicion() {
		return this.tmEdicion;
	}

	public void setTmEdicion(Serializable tmEdicion) {
		this.tmEdicion = tmEdicion;
	}

	@Column(name = "CD_CREADOR", scale = 0)
	public BigDecimal getCdCreador() {
		return this.cdCreador;
	}

	public void setCdCreador(BigDecimal cdCreador) {
		this.cdCreador = cdCreador;
	}

	@Column(name = "CD_EDITOR", scale = 0)
	public BigDecimal getCdEditor() {
		return this.cdEditor;
	}

	public void setCdEditor(BigDecimal cdEditor) {
		this.cdEditor = cdEditor;
	}

	@Column(name = "NU_TUB_OFERTA", scale = 0)
	public BigDecimal getNuTubOferta() {
		return this.nuTubOferta;
	}

	public void setNuTubOferta(BigDecimal nuTubOferta) {
		this.nuTubOferta = nuTubOferta;
	}

	@Column(name = "NU_TUB_VISITA", scale = 0)
	public BigDecimal getNuTubVisita() {
		return this.nuTubVisita;
	}

	public void setNuTubVisita(BigDecimal nuTubVisita) {
		this.nuTubVisita = nuTubVisita;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpic060ExpTuberia")
	public Set<Tpic061ExpOperaci> getTpic061ExpOperacis() {
		return this.tpic061ExpOperacis;
	}

	public void setTpic061ExpOperacis(Set<Tpic061ExpOperaci> tpic061ExpOperacis) {
		this.tpic061ExpOperacis = tpic061ExpOperacis;
	}

}
