package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Tpic061ExpOperaciId generated by hbm2java
 */
@Embeddable
public class Tpic061ExpOperaciId implements java.io.Serializable {

	private String cdOpe;
	private BigDecimal cdTub;

	public Tpic061ExpOperaciId() {
	}

	public Tpic061ExpOperaciId(String cdOpe, BigDecimal cdTub) {
		this.cdOpe = cdOpe;
		this.cdTub = cdTub;
	}

	@Column(name = "CD_OPE", nullable = false, length = 10)
	public String getCdOpe() {
		return this.cdOpe;
	}

	public void setCdOpe(String cdOpe) {
		this.cdOpe = cdOpe;
	}

	@Column(name = "CD_TUB", nullable = false, scale = 0)
	public BigDecimal getCdTub() {
		return this.cdTub;
	}

	public void setCdTub(BigDecimal cdTub) {
		this.cdTub = cdTub;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Tpic061ExpOperaciId))
			return false;
		Tpic061ExpOperaciId castOther = (Tpic061ExpOperaciId) other;

		return ((this.getCdOpe() == castOther.getCdOpe()) || (this.getCdOpe() != null && castOther.getCdOpe() != null
				&& this.getCdOpe().equals(castOther.getCdOpe())))
				&& ((this.getCdTub() == castOther.getCdTub()) || (this.getCdTub() != null
						&& castOther.getCdTub() != null && this.getCdTub().equals(castOther.getCdTub())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCdOpe() == null ? 0 : this.getCdOpe().hashCode());
		result = 37 * result + (getCdTub() == null ? 0 : this.getCdTub().hashCode());
		return result;
	}

}
