package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpic061ExpOperaci generated by hbm2java
 */
@Entity
@Table(name = "TPIC061_EXP_OPERACI")
public class Tpic061ExpOperaci implements java.io.Serializable {

	private Tpic061ExpOperaciId id;
	private Tpic060ExpTuberia tpic060ExpTuberia;
	private Date fhOpeDesembolso;
	private BigDecimal nuOpeMontoDesembolso;
	private String txOpeCliente;
	private String txOpeAsesor;
	private String txOpeObservacion;

	public Tpic061ExpOperaci() {
	}

	public Tpic061ExpOperaci(Tpic061ExpOperaciId id, Tpic060ExpTuberia tpic060ExpTuberia) {
		this.id = id;
		this.tpic060ExpTuberia = tpic060ExpTuberia;
	}

	public Tpic061ExpOperaci(Tpic061ExpOperaciId id, Tpic060ExpTuberia tpic060ExpTuberia, Date fhOpeDesembolso,
			BigDecimal nuOpeMontoDesembolso, String txOpeCliente, String txOpeAsesor, String txOpeObservacion) {
		this.id = id;
		this.tpic060ExpTuberia = tpic060ExpTuberia;
		this.fhOpeDesembolso = fhOpeDesembolso;
		this.nuOpeMontoDesembolso = nuOpeMontoDesembolso;
		this.txOpeCliente = txOpeCliente;
		this.txOpeAsesor = txOpeAsesor;
		this.txOpeObservacion = txOpeObservacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cdOpe", column = @Column(name = "CD_OPE", nullable = false, length = 10)),
			@AttributeOverride(name = "cdTub", column = @Column(name = "CD_TUB", nullable = false, scale = 0)) })
	public Tpic061ExpOperaciId getId() {
		return this.id;
	}

	public void setId(Tpic061ExpOperaciId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_TUB", nullable = false, insertable = false, updatable = false)
	public Tpic060ExpTuberia getTpic060ExpTuberia() {
		return this.tpic060ExpTuberia;
	}

	public void setTpic060ExpTuberia(Tpic060ExpTuberia tpic060ExpTuberia) {
		this.tpic060ExpTuberia = tpic060ExpTuberia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_OPE_DESEMBOLSO", length = 7)
	public Date getFhOpeDesembolso() {
		return this.fhOpeDesembolso;
	}

	public void setFhOpeDesembolso(Date fhOpeDesembolso) {
		this.fhOpeDesembolso = fhOpeDesembolso;
	}

	@Column(name = "NU_OPE_MONTO_DESEMBOLSO", precision = 15)
	public BigDecimal getNuOpeMontoDesembolso() {
		return this.nuOpeMontoDesembolso;
	}

	public void setNuOpeMontoDesembolso(BigDecimal nuOpeMontoDesembolso) {
		this.nuOpeMontoDesembolso = nuOpeMontoDesembolso;
	}

	@Column(name = "TX_OPE_CLIENTE", length = 50)
	public String getTxOpeCliente() {
		return this.txOpeCliente;
	}

	public void setTxOpeCliente(String txOpeCliente) {
		this.txOpeCliente = txOpeCliente;
	}

	@Column(name = "TX_OPE_ASESOR", length = 50)
	public String getTxOpeAsesor() {
		return this.txOpeAsesor;
	}

	public void setTxOpeAsesor(String txOpeAsesor) {
		this.txOpeAsesor = txOpeAsesor;
	}

	@Column(name = "TX_OPE_OBSERVACION", length = 300)
	public String getTxOpeObservacion() {
		return this.txOpeObservacion;
	}

	public void setTxOpeObservacion(String txOpeObservacion) {
		this.txOpeObservacion = txOpeObservacion;
	}

}
