package entities;
// Generated 08/09/2016 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tpic065ExpDregist generated by hbm2java
 */
@Entity
@Table(name = "TPIC065_EXP_DREGIST")
public class Tpic065ExpDregist implements java.io.Serializable {

	private BigDecimal cdRegistro;
	private Tpic064ExpRoperac tpic064ExpRoperac;

	public Tpic065ExpDregist() {
	}

	public Tpic065ExpDregist(Tpic064ExpRoperac tpic064ExpRoperac) {
		this.tpic064ExpRoperac = tpic064ExpRoperac;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tpic064ExpRoperac"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "CD_REGISTRO", unique = true, nullable = false, scale = 0)
	public BigDecimal getCdRegistro() {
		return this.cdRegistro;
	}

	public void setCdRegistro(BigDecimal cdRegistro) {
		this.cdRegistro = cdRegistro;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tpic064ExpRoperac getTpic064ExpRoperac() {
		return this.tpic064ExpRoperac;
	}

	public void setTpic064ExpRoperac(Tpic064ExpRoperac tpic064ExpRoperac) {
		this.tpic064ExpRoperac = tpic064ExpRoperac;
	}

}
